/**
 * Diffbot Enhance Service
 * Enhance is an API to find a person or organization in the Knowledge Graph using partial data
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: support@diffbot.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EnhanceResponse from '../com.diffbot.kg.enhance.openapi.model/EnhanceResponse';
import RequestError from '../com.diffbot.kg.enhance.openapi.model/RequestError';

/**
* EnhanceLiveEndpoint service.
* @module com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.api/EnhanceLiveEndpointApi
* @version 1.0.0-rc.03
*/
export default class EnhanceLiveEndpointApi {

    /**
    * Constructs a new EnhanceLiveEndpointApi. 
    * @alias module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.api/EnhanceLiveEndpointApi
    * @class
    * @param {module:com.diffbot.kg.enhance.openapi.invoker/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.diffbot.kg.enhance.openapi.invoker/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the enhance operation.
     * @callback module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.api/EnhanceLiveEndpointApi~enhanceCallback
     * @param {String} error Error message, if any.
     * @param {module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.model/EnhanceResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Live Enhance Endpoint
     * Enhance endpoint to find person or organization using partial data
     * @param {Object} opts Optional parameters
     * @param {String} opts.token Diffbot Token
     * @param {module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.model/String} opts.type Diffbot entity type
     * @param {String} opts.id DiffbotId of entity to enhance. Parameter can be used with types `Person` and `Organization`
     * @param {String} opts.name Name of the entity to enhance. Parameter can be used with types `Person` and `Organization`
     * @param {String} opts.url Origin or homepage URI of entity to enhance. Parameter can be used with types `Person` and `Organization`
     * @param {String} opts.phone Phone of the entity to enhance. Parameter can be used with types `Person` and `Organization`
     * @param {String} opts.email Email of the entity to enhance. Parameter can be used only with type `Person`
     * @param {String} opts.description Description of the entity to enhance. Parameter can be used with types `Person` and `Organization`
     * @param {String} opts.employer Employer of the entity to enhance. Parameter can be used only with type `Person`
     * @param {String} opts.title Title of the entity to enhance. Parameter can be used only with type `Person`
     * @param {String} opts.school School of the entity to enhance. Parameter can be used only with type `Person`
     * @param {String} opts.location Location of the entity to enhance. Parameter can be used with types `Person` and `Organization`
     * @param {String} opts.mode `mode=refresh` indicates that Diffbot will attempt to recrawl all the origins of the identified entity and reconstruct the returned entity from this refreshed data.
     * @param {String} opts.nonCanonicalFacts `nonCanonicalFacts=true` returns non-canonical facts.
     * @param {String} opts.jsonmode `jsonmode=extended` returns origin information for facts.
     * @param {String} opts.leadIQToken leadIQ token
     * @param {String} opts.rocketReachToken rocketReach token
     * @param {String} opts.xDiffbotRequestId Request UUID for tracking. If available, will be set on response.
     * @param {module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.api/EnhanceLiveEndpointApi~enhanceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.model/EnhanceResponse}
     */
    enhance(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'token': opts['token'],
        'type': opts['type'],
        'id': opts['id'],
        'name': opts['name'],
        'url': opts['url'],
        'phone': opts['phone'],
        'email': opts['email'],
        'description': opts['description'],
        'employer': opts['employer'],
        'title': opts['title'],
        'school': opts['school'],
        'location': opts['location'],
        'mode': opts['mode'],
        'nonCanonicalFacts': opts['nonCanonicalFacts'],
        'jsonmode': opts['jsonmode'],
        'leadIQToken': opts['leadIQToken'],
        'rocketReachToken': opts['rocketReachToken']
      };
      let headerParams = {
        'X-Diffbot-RequestId': opts['xDiffbotRequestId']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EnhanceResponse;
      return this.apiClient.callApi(
        '/kg/enhance_endpoint', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
