/**
 * Diffbot Enhance Service
 * Enhance is an API to find a person or organization in the Knowledge Graph using partial data
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: support@diffbot.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BulkjobAccepted model module.
 * @module com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.model/BulkjobAccepted
 * @version 1.0.0-rc.02
 */
class BulkjobAccepted {
    /**
     * Constructs a new <code>BulkjobAccepted</code>.
     * @alias module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.model/BulkjobAccepted
     */
    constructor() { 
        
        BulkjobAccepted.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BulkjobAccepted</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.model/BulkjobAccepted} obj Optional instance to populate.
     * @return {module:com.diffbot.kg.enhance.openapi.invoker/com.diffbot.kg.enhance.openapi.model/BulkjobAccepted} The populated <code>BulkjobAccepted</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkjobAccepted();

            if (data.hasOwnProperty('job_id')) {
                obj['job_id'] = ApiClient.convertToType(data['job_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Bulkjob Id for checking status and downloading results
 * @member {String} job_id
 */
BulkjobAccepted.prototype['job_id'] = undefined;






export default BulkjobAccepted;

